# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LanternHeadless < Formula
  desc "Lantern Headless Client"
  homepage "https://github.com/getlantern/lantern-headless-client"
  version "1.1.0"
  license "GPL"

  on_macos do
    url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.1.0/lantern-headless-all.dmg"
    sha256 "b506f3faeee6103657de1c433e0ff48d3ddaa7be3ecdf65065a01343dd882cf5"

    def install
      bin.install "lantern-headless"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.1.0/lantern-headless_1.1.0_linux_amd64.tar.gz"
      sha256 "492bcf213dbb391e81e8cd0cfd730996de53ae6b3766cfb362448608a6209ce8"
      def install
        bin.install "lantern-headless"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.1.0/lantern-headless_1.1.0_linux_arm64.tar.gz"
      sha256 "a91b8dbd8ce31d6d79f5680570a91da9f38624c55ebcc990e77d189cfe06cd5e"
      def install
        bin.install "lantern-headless"
      end
    end
  end
end
