# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LanternHeadless < Formula
  desc "Lantern Headless Client"
  homepage "https://github.com/getlantern/lantern-headless-client"
  version "1.0.24"
  license "GPL"

  on_macos do
    url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.0.24/lantern-headless-all.dmg"
    sha256 "ad29a13fa27836752a2a34191a74611f2a8efd6d266799fc9c50567fffb6310a"

    def install
      bin.install "lantern-headless"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.0.24/lantern-headless_1.0.24_linux_amd64.tar.gz"
        sha256 "541b1ee0d75dc0a8b603c42a10bb736644f1310c9622c369e3c165b8a2f8b6db"

        def install
          bin.install "lantern-headless"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.0.24/lantern-headless_1.0.24_linux_arm64.tar.gz"
        sha256 "e530cee65345e94282cc374a75c9912655044fc5a31de57b3caf5a871cde1d27"

        def install
          bin.install "lantern-headless"
        end
      end
    end
  end
end
