# This file was generated by GoReleaser. DO NOT EDIT.
cask "lantern-headless" do
  name "lantern-headless"
  desc "Lantern Headless Client"
  homepage "https://github.com/getlantern/lantern-headless-client"
  version "1.2.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lantern-headless"

  on_linux do
    on_intel do
      url "https://github.com/getlantern/lantern-headless-client/releases/download/v#{version}/lantern-headless_#{version}_linux_amd64.tar.gz"
      sha256 "55c9af54f0d366f38702b527c433b19fcf5f3fb902a54c2f6766c9ae4064db3f"
    end
    on_arm do
      url "https://github.com/getlantern/lantern-headless-client/releases/download/v#{version}/lantern-headless_#{version}_linux_arm64.tar.gz"
      sha256 "f310fd2f1e5c46563eba4f609a1e0105abd119370ad95ca965eba5ad1d971736"
    end
  end

  # No zap stanza required
end
